# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/IfcOpenHouse',
                'doc_host': 'https://cvillagrasa.github.io',
                'git_url': 'https://github.com/cvillagrasa/IfcOpenHouse',
                'lib_path': 'IfcOpenHouse'},
  'syms': {'IfcOpenHouse.core': {'IfcOpenHouse.core.foo': ('core.html#foo', 'IfcOpenHouse/core.py')}}}
